name: utilities
description: Date, string, number, file helpers and formatting utilities shared across both applications.
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  core:
    path: ../core
  flutter:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0
