name: sanad_client
description: Sanad client-facing mobile application.
version: 1.0.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  app_assets:
    path: ../../packages/app_assets
  app_logger:
    path: ../../packages/app_logger
  account_settings:
    path: ../../packages/features/account_settings
  auth:
    path: ../../packages/features/auth
  core:
    path: ../../packages/core
  cupertino_icons: ^1.0.8
  design_system:
    path: ../../packages/design_system
  shared_ui:
    path: ../../packages/shared_ui
  dio: ^5.10.0
  easy_localization: ^3.0.8
  equatable: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^10.3.1
  go_router: ^17.3.0
  hive_ce: ^2.10.1
  hydrated_bloc: ^11.0.0
  localization:
    path: ../../packages/localization
  network:
    path: ../../packages/network
  path_provider: ^2.1.5
  provider: ^6.1.5
  storage:
    path: ../../packages/storage

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/app_icon.png

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash_logo.png
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/splash/