name: api
description: Remote API layer — endpoints, DTOs, request/response models, remote data sources, repositories.
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  core:
    path: ../core
  equatable: ^2.1.0
  flutter:
    sdk: flutter
  fpdart: ^1.2.0
  network:
    path: ../network
  shared_models:
    path: ../shared_models

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0
