/// Authentication — passwordless email OTP, session, auth BLoC, and status.
library;

export 'src/auth/auth_status.dart';
export 'src/auth/auth_status_notifier.dart';
export 'src/data/models/auth_response_model.dart';
export 'src/data/models/profiles/auth_profile_model.dart';
export 'src/data/models/responses/auth_account_settings_response_dto.dart';
export 'src/data/models/responses/auth_session_response_dto.dart';
export 'src/di/auth_di.dart';
export 'src/domain/entities/auth_account_settings_entity.dart';
export 'src/domain/entities/auth_profile_entity.dart';
export 'src/domain/entities/auth_response_entity.dart';
export 'src/domain/entities/permission_entity.dart';
export 'src/domain/entities/user_entity.dart';
export 'src/domain/enums/auth_session_status.dart';
export 'src/domain/enums/user_type.dart';
export 'src/domain/repositories/auth_repository.dart';
export 'src/domain/usecases/check_signin_status_usecase.dart';
export 'src/domain/usecases/delete_account_usecase.dart';
export 'src/domain/usecases/logout_usecase.dart';
export 'src/domain/usecases/request_email_otp_usecase.dart';
export 'src/domain/usecases/sign_in_with_google_usecase.dart';
export 'src/domain/usecases/usecase_params.dart';
export 'src/domain/usecases/verify_email_otp_usecase.dart';
export 'src/module/auth_module.dart';
export 'src/presentation/bloc/auth/auth_bloc.dart';
export 'src/presentation/pages/auth_page.dart';
export 'src/presentation/pages/email_otp_page.dart';
export 'src/presentation/pages/splash_page.dart';
export 'src/presentation/session/session_builder.dart';
export 'src/presentation/session/session_context_extension.dart';
export 'src/presentation/session/session_selector.dart';
export 'src/presentation/widgets/app_header.dart';
export 'src/routes/auth_routes.dart';
export 'src/routing/auth_shell.dart';
export 'src/session/session_manager.dart';
