// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLRKfvc4vGnsz3XRVmUuL0ANheygJHZ2o',
    appId: '1:53289695434:android:5c0b430ebefa5c3ebd1c33',
    messagingSenderId: '53289695434',
    projectId: 'sanad-da77a',
    storageBucket: 'sanad-da77a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAZq0xQv8-YQc4uSX77-2Qz41qhcCl5UE',
    appId: '1:53289695434:ios:199576590b48bc40bd1c33',
    messagingSenderId: '53289695434',
    projectId: 'sanad-da77a',
    storageBucket: 'sanad-da77a.firebasestorage.app',
    androidClientId: '53289695434-okud006675uakupahj6qf66qp8emc4go.apps.googleusercontent.com',
    iosClientId: '53289695434-704152k5t3gsf0l36c9s9utllaolft6e.apps.googleusercontent.com',
    iosBundleId: 'com.sanad.client',
  );
}
